spring:
  main:
    web-application-type: reactive
  kafka:
      consumer:
        bootstrap-servers: 172.16.16.5:9092
        group-id: timon-raw78i
        auto-offset-reset: earliest
        request-timeout-ms: 6000
        heartbeat-interval-ms: 2000
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topics: timon-alert,users,config
  redis:
    host: 172.16.16.15
    port: 6379
    timeout: 20000
    password:
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
server:
  port: 6088
  http2:
    enabled: true

device:
  cm:
    url: http://172.16.16.188:8090/api/device
  class:
    prefix: com.timon.domain
  category: Group550, group550, TE50, Bird666, HDX, SwitchHuawei, SwitchCisco
  msg:
    group550:
      type: Group550
    bird666:
      type: Bird666
    TE50:
      type: TE50
    HDX:
      type: HDX
  prefix:
    metric: "METRIC:"
    location: "location:"