#logging:
#  level:
#    org.springframework: ERROR
#    com.timon: DEBUG
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
#    file: "%d %p %c{1.} [%t] %m%n"
#  file: app.log


spring:
  profiles:
    active: dev
  kafka:
    consumer:
      bootstrap-servers: 172.16.16.5:9092
      group-id: timon-alert767
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.16.16.5:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      buffer-memory: 33554432
      batch-size: 16384
      acks: all
      compression-type: snappy
    topic:
      # alert-raw: timon.device.raw
      alert-raw: redis
      heartbeat: users
    topics: redis,user,rawdata
  redis:
    host: 172.16.16.15
    port: 6379
    timeout: 20000
    password:
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1


device:
  class:
    prefix: com.timon.domain
  category: Group550, group550, TE50, Bird666, HDX, SwitchHuawei, SwitchCisco
  msg:
    group550:
      type: Group550
    bird666:
      type: Bird666
    TE50:
      type: TE50
    HDX:
      type: HDX
  prefix:
    metric: _METRIC_
ruleengine:
  rulePriorityThreshold: 20
  skipOnFirstAppliedRule: false
  skipOnFirstFailedRule: false
  skipOnFirstNonTriggeredRule: false

rule:
  class:
    prefix: com.timon.rule.


