spring:
  kafka:
    bootstrap-servers: 172.16.16.5:9092
    consumer:
      bootstrap-servers: 172.16.16.5:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.16.16.5:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      buffer-memory: 33554432
      batch-size: 16384
      acks: all
      compression-type: snappy
    topic:
      alert-raw: test

kafka:
  topics:
    -
      name: testing-auto-setup
      num-partitions: 1
      replication-factor: 1
    -
      name: another-test
      num-partitions: 1
      replication-factor: 1

device:
  category: group550, te50

