#server:
#  port: 8088
#  servlet:
#    contextPath: /alert
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main:
    # web-application-type: reactive
    # web-application-type: servlet
    allow-bean-definition-overriding: true
  ansi:
    enabled: DETECT
  profiles:
    active: dev
  kafka:
    consumer:
      bootstrap-servers: 172.16.16.5:9092
      group-id: timon-rawc
      auto-offset-reset: earliest
      request-timeout-ms: 6000
      heartbeat-interval-ms: 2000
      enable-auto-commit: true
      auto-commit-interval-ms: 1000
      partition-assignment-strategy: Range
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.16.16.5:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      buffer-memory: 33554432
      batch-size: 16384
      acks: all
      compression-type: snappy
      topic: timon-alert
    topics: testrawdata,users
  redis:
    host: 172.16.16.15
    port: 6379
    timeout: 20000
    password:
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
  jpa:
      hibernate:
         ddl-auto: update
         show-sql: true
  datasource:
      url: jdbc:mysql://172.16.16.6:3306/timon?characterEncoding=utf-8&serverTimezone=UTC&useLegacyDatetimeCode=false&rewriteBatchedStatements=true
      username: root
      password: 123456
      hikari:
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
      properties:
        hibernate:
          jdbc:
            batch_size: 10
          generate_statistics: true


device:
  class:
    prefix: com.timon.domain
  category: Group550, group550, TE50, Bird666, HDX, SwitchHuawei, SwitchCisco
  msg:
    group550:
      type: Group550
    bird666:
      type: Bird666
    TE50:
      type: TE50
    HDX:
      type: HDX
  prefix:
    metric: "METRIC:"
    location: "location:"
ruleengine:
  rulePriorityThreshold: 20
  skipOnFirstAppliedRule: false
  skipOnFirstFailedRule: false
  skipOnFirstNonTriggeredRule: false

rule:
  class:
    prefix: com.timon.rule.


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"




#logging:
#  level:
#    root: INFO
#    org.springframework: ERROR
#    com.timon: DEBUG
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
#    file: "%d %p %c{1.} [%t] %m%n"
#  file: target/app.log
#  appenders:
#    maxFileSize: 10MB
#    maxHistory: 3

